### ISSUE TITLE
Moodle description displayed twice at top when taking the questionnaire

### ISSUE THREAD

**Issue by jaschrock** [PoetOS/moodle-mod_questionnaire#420]
When clicking on the survey, you see the description repeated. 
This is on Moodle 4.0.3 with all plugins up-to-date. This seems to be true on all of our created surveys since the upgrade to Moodle 4.

![questionnair - description repeated](https://user-images.githubusercontent.com/24418146/189180801-68ff19af-8b03-430c-b947-2274549dcc2f.JPG)

**Comment by lucaboesch** [comment]
#428 fixes this.

**Comment by rezeau** [comment]
@lucaboesch 
No, it does not fix the complete issue in Moodle 4.x. 
When Questionnaire is displayed to a student, **3** elements are superfluous and **should not be displayed**, namely:
1.- intro/description, as fixed by @NinaHerman in #428 
2.- questionnairename, as fixed by @emilevirus in #434 (but it should add the Moodle version condition as peer #428)
3.- secondary-navigation: don't know where this is added and should be removed (from student view)

**Comment by lucaboesch** [comment]
Okay, thanks for clearing that up, @rezeau.
Maybe you could directly inline comment in #434 on how to add the Moodle version condition from #428 ?
Then the contributor @emilevirus can maybe rework the patch.

**Comment by rezeau** [comment]
> Okay, thanks for clearing that up, @rezeau. Maybe you could directly inline comment in #434 on how to add the Moodle version condition from #428 ? Then the contributor @emilevirus can maybe rework the patch.

@lucaboesch Hopefully @emilevirus will see this exchange. But anyway what is needed is some re-working of the Questionnaire header display in Moodle 4 taking into account all 3 problems I mentioned above.

**Comment by jaschrock** [comment]
When will this be pushed up to moodle so it is available directly as a plugin update? I upgraded to 4.1 and still don't see a fix for it.

**Comment by mchurchward** [comment]
Fixed with above PR.
