### ISSUE TITLE
Anonymous questionnaires go to grade book before questionnaire closes, allowing for potentially non-anonymous results.

### ISSUE THREAD

**Issue by ande7587** [PoetOS/moodle-mod_questionnaire#57]
An issue that we have observed can be reproduced as follows:
1. Create an anonymous questionnaire with a grade attached to it.
2. Have a student answer the questionnaire.
3. Observe that when the student answers the questionnaire, the instructor can see that the student has a grade, meaning an instructor can tell who submitted it if one person responds before anybody else.  This compromises the idea of anonymous results.

It would be ideal if the grades were not pushed to the grade book until after the questionnaire closed.

**Comment by mchurchward** [comment]
Hi. Can you create a tracker item for this? Use the CONTRIB project and the "questionnaire" component.
I think we need to consider what an anonymous questionnaire is as well. I think it could be argued that there should never be grades if a questionnaire is anonymous, since there should be no connection to a user.

**Comment by mchurchward** [comment]
See CONTRIB-6113
